#!/bin/bash
cd ~/rtmcore-node/bin
wget https://github.com/Raptor3um/Raptoreum/releases/download/1.0/raptoreum-1.0-x86_64-linux-gnu.tar.gz
tar -xvzf raptoreum-1.0-x86_64-linux-gnu.tar.gz
cp raptoreum-1.0/bin/raptoreumd .
exit 0
